import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Appbar from "@/components/appbar";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme/theme-provider";
import SidebarServer from "@/components/sidebar/sidebar-server";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("flex min-h-screen flex-col", inter.className)}>
        <Providers>
          <Appbar />
          <div className="mx-auto flex w-full max-w-screen-2xl flex-1">
            <SidebarServer />
            <main className="w-full px-4 pt-8">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
